# btop defaults for web dashboard mode
shown_boxes = "cpu mem net proc gpu0"
show_gpu_info = "On"
nvml_measure_pcie_speeds = True
update_ms = 1000

check_temp = True
show_coretemp = True
show_cpu_freq = True

proc_sorting = "cpu direct"
proc_reversed = False
proc_tree = False
proc_filter_kernel = False
proc_mem_bytes = True
proc_cpu_graphs = True

show_disks = True
show_io_stat = True
io_mode = False

net_auto = True
net_sync = True
